export const actionsListBase = {
    SET_THEME_DARK: 'SET_THEME_DARK',
    SET_THEME_LIGHT: 'SET_THEME_LIGHT',
    SET_THEME_TOGGLE: 'SET_THEME_TOGGLE',
    SET_LANG_EN: 'SET_LANG_EN',
    SET_LANG_RU: 'SET_LANG_RU',
    SET_NAV_OPEN_MOB: 'SET_NAV_OPEN_MOB',
    SET_NAV_CLOSE_MOB: 'SET_NAV_CLOSE_MOB',
    SET_NAV_TOGGLE_MOB: 'SET_NAV_TOGGLE_MOB',
    SET_NAV_OPEN_DT: 'SET_NAV_OPEN_DT',
    SET_NAV_CLOSE_DT: 'SET_NAV_CLOSE_DT',
    SET_NAV_TOGGLE_DT: 'SET_NAV_TOGGLE_DT',
}
