export const LOAD_ALL_DATA = 'LOAD_ALL_DATA'

export const SET_THEME_DARK = 'SET_THEME_DARK'
export const SET_THEME_LIGHT = 'SET_THEME_LIGHT'
export const SET_THEME_TOGGLE = 'SET_THEME_TOGGLE'

export const SET_LANG_EN = 'SET_LANG_EN'
export const SET_LANG_RU = 'SET_LANG_RU'

export const SET_NAV_OPEN = 'SET_NAV_OPEN'
export const SET_NAV_CLOSE = 'SET_NAV_CLOSE'
export const SET_NAV_TOGGLE = 'SET_NAV_TOGGLE'


export const LOAD_PORTFOLIOS = 'LOAD_PORTFOLIOS'
export const SAVE_PORTFOLIOS = 'SAVE_PORTFOLIOS'
export const SET_PORTFOLIOS_STATUS_ERROR = 'SET_PORTFOLIOS_STATUS_ERROR'
export const SET_PORTFOLIOS_STATUS_SUCCESS = 'SET_PORTFOLIOS_STATUS_SUCCESS'
export const SET_PORTFOLIOS_STATUS_IDLE = 'SET_PORTFOLIOS_STATUS_IDLE'
export const SET_PORTFOLIOS_STATUS_LOADING = 'SET_PORTFOLIOS_STATUS_LOADING'
export const SET_PORTFOLIOS_STATUS_SAVING = 'SET_PORTFOLIOS_STATUS_SAVING'



//export const LOAD_DATA = 'LOAD_DATA'
//export const SET_DATA = 'SET_DATA'
//export const SET_LOAD_DATA_STATUS = 'LOAD_DATA_STATUS'
export const LOAD_DATA_FIBERS = 'LOAD_DATA_FIBERS'
export const SET_LOAD_DATA_STATUS_FIBERS = 'LOAD_DATA_STATUS_FIBERS'
export const SET_DATA_FIBERS = 'SET_DATA'

export const LOAD_DATA_SLIDERMAX = 'LOAD_DATA_SLIDERMAX'
export const SET_LOAD_DATA_STATUS_SLIDERMAX = 'SET_LOAD_DATA_STATUS_SLIDERMAX'
export const SET_DATA_SLIDERMAX = 'SET_DATA_SLIDERMAX'
