export const SET_THEME_DARK = 'SET_THEME_DARK'
export const SET_THEME_LIGHT = 'SET_THEME_LIGHT'
export const SET_THEME_TOGGLE = 'SET_THEME_TOGGLE'

export const SET_LANG_EN = 'SET_LANG_EN'
export const SET_LANG_RU = 'SET_LANG_RU'

export const SET_NAV_OPEN = 'SET_NAV_OPEN'
export const  SET_NAV_CLOSE = 'SET_NAV_CLOSE'
export const  SET_NAV_TOGGLE = 'SET_NAV_TOGGLE'


export const  SET_PORTFOLIOS = 'SET_PORTFOLIOS'
export const  SET_PORTFOLIOS_STATUS_ERROR = 'SET_PORTFOLIOS_STATUS_ERROR'
export const  SET_PORTFOLIOS_STATUS_SUCCESS = 'SET_PORTFOLIOS_STATUS_SUCCESS'
export const  SET_PORTFOLIOS_STATUS_IDLE = 'SET_PORTFOLIOS_STATUS_IDLE'
export const  SET_PORTFOLIOS_STATUS_LOADING = 'SET_PORTFOLIOS_STATUS_LOADING'

