name: Test, deploy to EC2
on: 
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
jobs: 
  deploy:
    runs-on: ubuntu-latest
    env:
      mongoUri: ${{ secrets.MONGO_URI }}
      jwtSecret: ${{ secrets.JWT_SECRET }}
      admEmail: ${{ secrets.ADM_EMAIL }}
      dbName: ${{ secrets.DB_NAME }}
      tgToken: ${{ secrets.TG_TOKEN }}
      chatId: ${{ secrets.CHAT_ID }}
      chatLink: ${{ secrets.CHAT_LINK }}
      pathToStorage: ${{ secrets.PATH_TO_STORAGE }}
      PORT: ${{ secrets.PORT }}
      awsAC: ${{ secrets.AWS_AC }}
      AWS.awsSAC: ${{ secrets.SAC }}
      awsRegion: ${{ secrets.AWS_REGION }}
      s3BucketName: ${{ secrets.S3_BUCKET_NAME }}
    steps:
      - name: Get repo code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install deps
        run: |
          cd backend
          npm ci --force
      - name: Build backend
        run: |
          cd backend
          npm run deploy
      - uses: actions/upload-artifact@v3
        with:
          name: built-files
          path: backend/dist
      - name: Get built project
        uses: actions/download-artifact@v3
        with:
          name: built-files
      - name: Deploy to Server 1
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: backend/dist/
          remote_path: /home/ubuntu/test2/
          remote_host: ${{ secrets.EC2_HOST }}
          remote_user: ${{ secrets.EC2_USERNAME }}
          remote_key: ${{ secrets.EC2_SSH_KEY }}
